#pragma config(Motor,  port1,           MobileLift,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           TopRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           TopLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BottomRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           ChassisRight,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           BottomLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           SprocketRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           ChassisLeft,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           SprocketLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Claw,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drivestraight(int speed, int duration) {
	motor[ChassisRight] = speed;
	motor[ChassisLeft] = speed;
	wait1Msec(duration);
}

void pointturn(int speed, int duration) {
	motor[ChassisRight] = speed;
	motor[ChassisLeft] = -speed;

}
void sprocketChain(int speed, int duration) {
	motor[SprocketLeft] = speed;
	motor[SprocketRight] = speed;
	wait1Msec(duration);
}

void crab(int speed, int duration) {
	motor[Claw] = speed;
	wait1Msec(duration);
}

void liftBtm(int speed, int duration) {
	motor[BottomLeft] = speed;
	motor[BottomRight] = speed;
	wait1Msec(duration);
}
void liftTop(int speed, int duration) {
	motor[TopLeft] = speed;
	motor[TopRight] = speed;
	wait1Msec(duration);
}
void liftAll(int speed, int duration) {
	motor[TopLeft] = speed;
	motor[TopRight] = speed;
	motor[BottomLeft] = speed;
	motor[BottomRight] = speed;
	wait1Msec(duration);
}
task main() {

	crab(60,600); //close claw
	drivestraight(70,1800); //drive forward
	crab(-60,500); //open claw
	drivestraight(70,950); //drive forward smore
	crab(70,1000); //close claw on mobile goallllllllllllll
	motor[Claw] = 40; //keep claw closed
	liftTop(70,500); //lift slightly off of the ground
	motor[TopRight] = 15; //keep claw lifted
	motor[TopLeft] = 15; //keep claw lifted
	pointturn(50,200); //turn a lil bit
	drivestraight(50,100); //go forward a lil bit
	pointturn(70,2450); //turn left a lot a bit
	drivestraight(70,3900); //drive to scoring zone
	pointturn(70,1200); //turn left quite a bit
	drivestraight(50,200); //drive straight just a lil bit
	liftTop(-20,800); //put mobile ghoul down
	crab(-70,700); //let go of mobile goal
	drivestraight(-70,500); // <<-- ^^^^




	while(true){
		motor[ChassisLeft] = vexRT[Ch3];
		motor[ChassisRight] = vexRT[Ch2];

		motor[BottomLeft] = vexRT[Ch3Xmtr2];
		motor[BottomRight] = vexRT[Ch3Xmtr2];
		motor[TopLeft] = vexRT[Ch2Xmtr2];
		motor[TopRight] = vexRT[Ch2Xmtr2];
		while( vexRT[Btn5UXmtr2]){
			motor[SprocketLeft] = 100;
			motor[SprocketRight] = 100;
		}
		while(vexRT[Btn5U]){
			motor[MobileLift] = 100;
		}
		while(vexRT[Btn5D]){
			motor[MobileLift] = -100;
		}
	}
}
